@rootUrl=https://localhost:44302


GET {{rootUrl}}/api/profile

###
@id = 2
GET {{rootUrl}}/api/profile/{{id}}

###
POST {{rootUrl}}/api/profile
Content-Type: application/json

{
  "Id" : 5,
  "Name" : "Kelle Morolo"
}